# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 20:03
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Company name')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adress')),
                ('post', models.PositiveIntegerField(blank=True, null=True, verbose_name='Postal code')),
                ('city', models.CharField(blank=True, max_length=40, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=40, null=True, verbose_name='State')),
                ('country', models.CharField(blank=True, max_length=40, null=True, verbose_name='Country')),
                ('tax_payer_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='Tax payer id')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=25, verbose_name='Invoice')),
                ('place', models.CharField(max_length=100, verbose_name='Place')),
                ('issued', models.DateField(verbose_name='Issued')),
                ('due_date', models.DateField(editable=False, null=True, verbose_name='Due date')),
                ('service_date', models.DateTimeField(verbose_name='Service date')),
                ('reference', models.CharField(max_length=100, verbose_name='Reference')),
                ('total_no_vat', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8, verbose_name='Znesek brez DDV')),
                ('total_with_vat', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8, verbose_name='Znesek z DDV')),
                ('payed', models.BooleanField(default=False, verbose_name='Plačano')),
                ('customer_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Customer', verbose_name='Costumer')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_no_vat', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Price without vat')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('currency', models.CharField(max_length=100, verbose_name='Currency')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Invoice')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Service')),
            ],
        ),
        migrations.CreateModel(
            name='Vat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Value added tax')),
                ('value', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8, verbose_name='Vat value')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='vat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Vat', verbose_name='Value added tax'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='services',
            field=models.ManyToManyField(through='invoice.ServicesQuantity', to='invoice.Service', verbose_name='Services'),
        ),
    ]
