# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 18:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Name')),
                ('last_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Last name')),
                ('company_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Company name')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adress')),
                ('post', models.PositiveIntegerField(blank=True, null=True, verbose_name='Postal code')),
                ('city', models.CharField(blank=True, max_length=40, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=40, null=True, verbose_name='State')),
                ('country', models.CharField(blank=True, max_length=40, null=True, verbose_name='Country')),
                ('tax_payer_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='Tax payer id')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=25, verbose_name='Invoice')),
                ('place', models.CharField(max_length=100, verbose_name='Place')),
                ('issued', models.DateField(verbose_name='Issued')),
                ('due_date', models.DateField(editable=False, null=True, verbose_name='Due date')),
                ('service_date', models.DateTimeField(verbose_name='Service date')),
                ('reference', models.CharField(max_length=100, verbose_name='Reference')),
                ('services', django.contrib.postgres.fields.jsonb.JSONField(default=[], verbose_name='Services')),
                ('total_no_vat', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8, verbose_name='Znesek brez DDV')),
                ('total_with_vat', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8, verbose_name='Znesek z DDV')),
                ('customer', django.contrib.postgres.fields.jsonb.JSONField(default=None, verbose_name='Customer')),
                ('payed', models.BooleanField(default=False, verbose_name='Plačano')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_no_vat', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Price without vat')),
                ('vat', django.contrib.postgres.fields.jsonb.JSONField(default=None, verbose_name='Vat')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('currency', models.CharField(max_length=100, verbose_name='Currency')),
            ],
        ),
        migrations.CreateModel(
            name='Vat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Value added tax')),
                ('value', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8, verbose_name='Vat value')),
            ],
        ),
    ]
